export const AELO_MUNICIPIOS_REGIOES: Record<string, string> = {
  "Araçatuba": "Araçatuba",
  "Birigüi": "Araçatuba",
  "Penápolis": "Araçatuba",
  "Araraquara": "Araraquara",
  "Ibitinga": "Araraquara",
  "Itápolis": "Araraquara",
  "Matão": "Araraquara",
  "São Carlos": "Araraquara",
  "Taquaritinga": "Araraquara",
  "Barretos": "Barretos",
  "Guaíra": "Barretos",
  "Barra Bonita": "Bauru",
  "Bauru": "Bauru",
  "Jaú": "Bauru",
  "Lins": "Bauru",
  "Americana": "Campinas",
  "Araras": "Campinas",
  "Bragança Paulista": "Campinas",
  "Campinas": "Campinas",
  "Conchal": "Campinas",
  "Hortolândia": "Campinas",
  "Indaiatuba": "Campinas",
  "Itapira": "Campinas",
  "Itupeva": "Campinas",
  "Jundiaí": "Campinas",
  "Leme": "Campinas",
  "Limeira": "Campinas",
  "Louveira": "Campinas",
  "Mococa": "Campinas",
  "Mogi Guaçu": "Campinas",
  "Mogi Mirim": "Campinas",
  "Monte Mor": "Campinas",
  "Nova Odessa": "Campinas",
  "Paulínia": "Campinas",
  "Piracicaba": "Campinas",
  "Pirassununga": "Campinas",
  "Rio Claro": "Campinas",
  "Santa Bárbara d'Oeste": "Campinas",
  "São João da Boa Vista": "Campinas",
  "Sumaré": "Campinas",
  "Valinhos": "Campinas",
  "Vinhedo": "Campinas",
  "Batatais": "Franca",
  "Franca": "Franca",
  "Itapeva": "Itapeva",
  "Assis": "Marília",
  "Marília": "Marília",
  "Barueri": "Metropolitana de São Paulo",
  "Cotia": "Metropolitana de São Paulo",
  "Itapevi": "Metropolitana de São Paulo",
  "Mogi das Cruzes": "Metropolitana de São Paulo",
  "Santana de Parnaíba": "Metropolitana de São Paulo",
  "Vargem Grande Paulista": "Metropolitana de São Paulo",
  "Dracena": "Presidente Prudente",
  "Presidente Epitácio": "Presidente Prudente",
  "Presidente Prudente": "Presidente Prudente",
  "Guariba": "Ribeirão Preto",
  "Monte Alto": "Ribeirão Preto",
  "Pitangueiras": "Ribeirão Preto",
  "Ribeirão Preto": "Ribeirão Preto",
  "Serrana": "Ribeirão Preto",
  "Sertãozinho": "Ribeirão Preto",
  "Bady Bassitt": "São José do Rio Preto",
  "Catanduva": "São José do Rio Preto",
  "Fernandópolis": "São José do Rio Preto",
  "Mirassol": "São José do Rio Preto",
  "Novo Horizonte": "São José do Rio Preto",
  "Santa Fé do Sul": "São José do Rio Preto",
  "São José do Rio Preto": "São José do Rio Preto",
  "Votuporanga": "São José do Rio Preto",
  "Caçapava": "São José dos Campos",
  "São José dos Campos": "São José dos Campos",
  "Taubaté": "São José dos Campos",
  "Boituva": "Sorocaba",
  "Itapetininga": "Sorocaba",
  "Itu": "Sorocaba",
  "Salto": "Sorocaba",
  "São Manuel": "Sorocaba",
  "Sorocaba": "Sorocaba",
  "Tatuí": "Sorocaba",
  "Votorantim": "Sorocaba"
};

