import { useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import type { Divergence } from './validation-rules';

export function DivergencesGrid({ rows }: { rows: Divergence[] }) {
  const [error, setError] = useState(''); const [rule, setRule] = useState('');
  const errors = useMemo(() => [...new Set(rows.filter((r) => !rule || r.rule === rule).map((r) => r.error))].sort(), [rows, rule]);
  const rules = useMemo(() => [...new Set(rows.map((r) => r.rule))].sort(), [rows]);
  const filtered = rows.filter((r) => (!error || r.error === error) && (!rule || r.rule === rule));
  const fieldLabel: Record<string, string> = { building_id: 'ID Empreendimento', builder_name: 'Incorporadora', total_stock: 'Estoque total', standard: 'Padrão', price_private_area: 'Preço por m²', qty: 'Quantidade de unidades', down_payment_percentage: 'Percentual de entrada', number_of_installments: 'Número de parcelas', bank_financing: 'Financiamento bancário', interest_rate_tax: 'Taxa de juros', total_units: 'Total de unidades', sold: 'Unidades vendidas', release_price: 'Preço de lançamento', sold_in_period: 'Vendas no período', release_date: 'Data de lançamento', distractions: 'Distratos', private_area: 'Área privativa', price: 'Preço', number_bedroom: 'Número de dormitórios', garage: 'Vagas de garagem' };
  const download = () => { const data = filtered.map((r) => ({ 'ID Empreendimento': r.building_id, 'ID Tipologia': r.typology_id, Empreendimento: r.building_name, 'Área Privativa': r.private_area, Cidade: r.city, Status: r.status, Período: r.period, Campo: fieldLabel[r.field] ?? r.field, Erro: r.error, Valor: r.value, Regra: r.rule })); const wb = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(data), 'Divergências'); XLSX.writeFile(wb, 'divergencias-encontradas.xlsx'); };
  return <div className="space-y-2"><div className="vf-card flex flex-wrap items-end gap-3 p-3"><label className="text-[10pt]">Erro<select className="vf-select ml-2 h-8 min-w-64" value={error} onChange={(e) => setError(e.target.value)}><option value="">Todos</option>{errors.map((v) => <option key={v}>{v}</option>)}</select></label><label className="text-[10pt]">Regra<select className="vf-select ml-2 h-8 min-w-56" value={rule} onChange={(e) => { setRule(e.target.value); setError(''); }}><option value="">Todas</option>{rules.map((v) => <option key={v}>{v}</option>)}</select></label><button type="button" className="vf-btn" onClick={() => { setError(''); setRule(''); }}>Limpar filtros</button><button type="button" className="vf-btn" data-variant="primary" onClick={download}>Baixar Excel</button><span className="ml-auto text-[10pt] text-[var(--vf-muted)]">{filtered.length.toLocaleString('pt-BR')} divergências</span></div><div className="vf-card p-3 text-[10pt] leading-relaxed"><strong>Como as comparações são agrupadas:</strong> regras de empreendimento usam <code>building_id + período</code> (somando as tipologias da fotografia); regras de cidade usam <code>cidade + tipo do empreendimento + tipo de tipologia + padrão + dormitórios + período</code>. A validação considera a última fotografia disponível de cada empreendimento ou tipologia.</div><div className="vf-grid-wrap overflow-auto"><table className="vf-grid min-w-[1300px]"><thead><tr>{['Empreendimento','Área Privativa','Cidade','Status','Período','Campo','Erro'].map((h) => <th key={h}>{h}</th>)}<th className="vf-div-value">Valor</th></tr></thead><tbody>{filtered.map((r, i) => <tr key={`${r.building_id}-${r.typology_id}-${r.field}-${r.error}-${i}`}><td className="vf-div-building">{r.building_name}</td><td className="vf-div-area">{r.private_area == null ? '—' : r.private_area.toLocaleString('pt-BR')}</td><td className="vf-div-city">{r.city}</td><td className="vf-div-status">{r.status}</td><td className="vf-div-period">{r.period}</td><td className="vf-div-field">{fieldLabel[r.field] ?? r.field}</td><td className="vf-div-error">{r.error}</td><td className="vf-div-value">{r.value}</td></tr>)}</tbody></table>{filtered.length === 0 && <div className="p-6 text-center text-sm text-[var(--vf-muted)]">Nenhuma divergência para os filtros selecionados.</div>}</div></div>;
}
