import type { MethodStatus } from '../types';

export type PanoramaVisualFamily = 'cover' | 'static' | 'divider' | 'summary' | 'comparison-table' | 'trend-chart' | 'market-table' | 'participation' | 'price' | 'matrix' | 'narrative' | 'map' | 'closing';
export interface ReportPageDefinition { page: number; referenceSlide: number; sectionId: string; title: string; intention: string; visualFamily: PanoramaVisualFamily; contractKeys: string[]; methodologyStatus: MethodStatus | 'not_applicable'; }
export interface PanoramaSection { id: string; label: string; start: number; end: number; }

export const PANORAMA_SECTIONS: PanoramaSection[] = [
  { id: 'about', label: 'Sobre o SECOVI-SP', start: 6, end: 10 }, { id: 'launches', label: 'Análise de Lançamentos', start: 11, end: 19 }, { id: 'sales', label: 'Análise de Vendas', start: 20, end: 27 }, { id: 'market', label: 'Análise Geral do Mercado', start: 28, end: 29 }, { id: 'vertical', label: 'Análise do Mercado Residencial Vertical', start: 30, end: 46 }, { id: 'horizontal', label: 'Análise do Mercado Residencial Horizontal', start: 47, end: 49 }, { id: 'vgv', label: 'Análise do VGV Geral', start: 50, end: 51 }, { id: 'observations', label: 'Análises e Observações Sobre o Mercado', start: 52, end: 54 }, { id: 'location', label: 'Localização dos Empreendimentos', start: 55, end: 56 }, { id: 'consultants', label: 'Consultores do Estudo', start: 57, end: 62 },
];

type Definition = [string, string, PanoramaVisualFamily, string[], MethodStatus | 'not_applicable'];
const pages: Definition[] = [
  ['Pesquisa de mercado','Capa de pesquisa','cover',[],'not_applicable'],['Piracicaba','Capa municipal','cover',[],'not_applicable'],['Visão, missão e valores','Institucional','static',[],'not_applicable'],['Panorama imobiliário de {cidade}','Abertura da praça','cover',[],'not_applicable'],['Sumário','Orientação de leitura','summary',[],'not_applicable'],['Sobre o SECOVI-SP','Abertura institucional','divider',[],'not_applicable'],['Sobre o SECOVI-SP','Institucional','static',[],'not_applicable'],['Política da qualidade','Institucional','static',[],'not_applicable'],['Objetivos','Abertura','divider',[],'not_applicable'],['Objetivos do estudo','Objetivos editoriais','static',[],'not_applicable'],
  ['Análise de lançamentos','Abertura de bloco','divider',[],'not_applicable'],['Lançamentos por trimestre','Tabela comparativa','comparison-table',['launch.projects','launch.units','launch.vgv'],'reconciled'],['Lançamentos por ano','Tabela anual','comparison-table',['launch.projects','launch.units','launch.vgv'],'reconciled'],['Empreendimentos por trimestre e tipo','Série de empreendimentos','trend-chart',['launch.projects'],'reconciled'],['Empreendimentos verticais por padrão','Série por padrão','trend-chart',['launch.projects'],'reconciled'],['Unidades lançadas por trimestre e tipo','Série de unidades','trend-chart',['launch.units'],'reconciled'],['Unidades verticais por padrão','Série por padrão','trend-chart',['launch.units'],'reconciled'],['VGV lançado por trimestre e tipo','Série de VGV','trend-chart',['launch.vgv'],'open_method'],['VGV vertical por padrão','Série por padrão','trend-chart',['launch.vgv'],'open_method'],
  ['Análise de vendas','Abertura de bloco','divider',[],'not_applicable'],['Vendas por trimestre','Tabela comparativa','comparison-table',['sales.units','sales.vgv'],'assumed'],['Vendas por ano','Tabela anual','comparison-table',['sales.units','sales.vgv'],'assumed'],['Unidades vendidas por trimestre e tipo','Série de vendas','trend-chart',['sales.units'],'assumed'],['VGV vendido por trimestre e tipo','Série de VGV vendido','trend-chart',['sales.vgv'],'assumed'],['Unidades verticais vendidas por padrão','Série por padrão','trend-chart',['sales.units'],'assumed'],['VGV vertical vendido por padrão','Série por padrão','trend-chart',['sales.vgv'],'assumed'],['Oferta, lançamentos, vendas e IVV por área útil','Matriz de mercado','matrix',['ivv'],'reconciled'],
  ['Análise geral do mercado','Abertura de bloco','divider',[],'not_applicable'],['Mercado: vertical, horizontal e total','Resumo executivo','matrix',['stock.units','availability'],'assumed'],['Mercado residencial vertical','Abertura de bloco','divider',[],'not_applicable'],['Oferta lançada e final por padrão','Tabela de estoque','market-table',['stock.units','availability'],'assumed'],['Participação da oferta por padrão','Participação','participation',['stock.units'],'assumed'],['Oferta por coorte de lançamento','Coortes','market-table',['cohorts'],'open_method'],['Oferta por tipologia','Tipologias','market-table',['stock.units'],'assumed'],['Participação da oferta por tipologia','Participação','participation',['stock.units'],'assumed'],['Ticket, área e R$/m² por tipologia','Indicadores de preço','price',['prices'],'open_method'],['Preço por m² por tipologia','Gráfico de preço','price',['prices'],'open_method'],['Ticket, área e R$/m² por padrão','Indicadores de preço','price',['prices'],'open_method'],['Preço por m² por padrão','Gráfico de preço','price',['prices'],'open_method'],['Preço por m² ao longo do tempo','Série de preço','trend-chart',['prices'],'open_method'],['Oferta por ano e padrão','Matriz de coorte','matrix',['cohorts'],'open_method'],['Participação por ano e padrão','Participação','participation',['cohorts'],'open_method'],['Tempo de mercado e maturidade por padrão','Maturidade','market-table',['maturity'],'open_method'],['Participação por maturidade e padrão','Participação','participation',['maturity'],'open_method'],['Tempo de mercado e maturidade por tipologia','Maturidade','market-table',['maturity'],'open_method'],['Participação por maturidade e tipologia','Participação','participation',['maturity'],'open_method'],
  ['Mercado residencial horizontal','Abertura de bloco','divider',[],'not_applicable'],['Oferta horizontal por coorte','Coortes','market-table',['cohorts'],'open_method'],['Ticket, área e R$/m² horizontal','Indicadores de preço','price',['prices'],'open_method'],['VGV geral','Abertura de bloco','divider',[],'not_applicable'],['VGV ofertado, disponível e vendido por padrão','Matriz de VGV','matrix',['stock.vgv'],'open_method'],['Análises e observações','Abertura de bloco','divider',[],'not_applicable'],['Análise de mercado','Narrativa orientada por dados','narrative',['narrative.facts'],'assumed'],['Análise de mercado','Narrativa orientada por dados','narrative',['narrative.facts'],'assumed'],['Localização dos empreendimentos','Abertura de bloco','divider',[],'not_applicable'],['Mapa de empreendimentos verticais','Visualização geográfica','map',['locations'],'open_method'],['Consultores do estudo','Abertura','divider',[],'not_applicable'],['Créditos','Equipe e fontes','static',[],'not_applicable'],['Brain Inteligência Estratégica','Encerramento','closing',[],'not_applicable'],['Panorama imobiliário','Encerramento','closing',[],'not_applicable'],['Obrigado','Encerramento','closing',[],'not_applicable'],['Fontes, premissas e rastreabilidade','Encerramento técnico','closing',[],'not_applicable'],
];

export const PANORAMA_REPORT_MANIFEST: ReportPageDefinition[] = pages.map(([title, intention, visualFamily, contractKeys, methodologyStatus], index) => {
  const page = index + 1; const section = PANORAMA_SECTIONS.find((item) => page >= item.start && page <= item.end);
  return { page, referenceSlide: page, sectionId: section?.id ?? 'opening', title, intention, visualFamily, contractKeys, methodologyStatus };
});
