export type ReportTemplate = 'cover' | 'divider' | 'launch-table' | 'launch-chart' | 'summary' | 'method' | 'narrative' | 'map' | 'credits' | 'closing';
export interface ReportPageDefinition { page: number; title: string; intention: string; template: ReportTemplate; }
const pages: Array<[string, string, ReportTemplate]> = [
  ['Panorama imobiliário', 'Capa de pesquisa', 'cover'], ['Panorama imobiliário de {cidade}', 'Capa do município', 'cover'], ['Visão, missão e valores', 'Institucional', 'narrative'], ['Panorama imobiliário de {cidade}', 'Abertura da praça', 'divider'], ['Sumário', 'Orientação de leitura', 'summary'], ['Secovi', 'Abertura institucional', 'divider'], ['Secovi – Campinas', 'Institucional', 'narrative'], ['Política da qualidade', 'Institucional', 'narrative'], ['Objetivos', 'Abertura', 'divider'], ['Objetivos do estudo', 'Objetivos editoriais', 'narrative'],
  ['Lançamentos', 'Abertura de bloco', 'divider'], ['Lançamentos – comparação trimestral', 'Tabela comparativa', 'launch-table'], ['Lançamentos por ano', 'Tabela anual', 'launch-table'], ['Empreendimentos por trimestre e tipo', 'Série de empreendimentos', 'launch-chart'], ['Empreendimentos verticais por padrão', 'Série por padrão', 'launch-chart'], ['Unidades lançadas por trimestre e tipo', 'Série de unidades', 'launch-chart'], ['Unidades verticais por padrão', 'Série por padrão', 'launch-chart'], ['VGV lançado por trimestre e tipo', 'Série de VGV', 'launch-chart'], ['VGV vertical por padrão', 'Série por padrão', 'launch-chart'],
  ['Vendas', 'Abertura de bloco', 'divider'], ['Vendas – comparação trimestral', 'Tabela de vendas', 'method'], ['Vendas por ano', 'Tabela anual', 'method'], ['Unidades vendidas por trimestre e tipo', 'Série de vendas', 'method'], ['VGV vendido por trimestre e tipo', 'Série de VGV vendido', 'method'], ['Unidades verticais vendidas por padrão', 'Série por padrão', 'method'], ['VGV vertical vendido por padrão', 'Série por padrão', 'method'], ['Oferta, lançamentos, vendas e IVV por área útil', 'Matriz de mercado', 'method'],
  ['Mercado imobiliário', 'Abertura de bloco', 'divider'], ['Mercado: vertical, horizontal e total', 'Resumo executivo', 'summary'], ['Mercado vertical', 'Abertura de bloco', 'divider'], ['Oferta lançada e final por padrão', 'Tabela de estoque', 'method'], ['Participação da oferta por padrão', 'Participação', 'method'], ['Oferta por coorte de lançamento', 'Coortes', 'method'], ['Oferta por tipologia', 'Tipologias', 'method'], ['Participação da oferta por tipologia', 'Participação', 'method'], ['Ticket, área e R$/m² por tipologia', 'Indicadores de preço', 'method'], ['Preço por m² por tipologia', 'Gráfico de preço', 'method'], ['Ticket, área e R$/m² por padrão', 'Indicadores de preço', 'method'], ['Preço por m² por padrão', 'Gráfico de preço', 'method'], ['Preço por m² ao longo do tempo', 'Série de preço', 'method'], ['Oferta por ano e padrão', 'Matriz de coorte', 'method'], ['Participação por ano e padrão', 'Participação', 'method'], ['Tempo de mercado e maturidade por padrão', 'Maturidade', 'method'], ['Participação por maturidade e padrão', 'Participação', 'method'], ['Tempo de mercado e maturidade por tipologia', 'Maturidade', 'method'], ['Participação por maturidade e tipologia', 'Participação', 'method'],
  ['Mercado horizontal', 'Abertura de bloco', 'divider'], ['Oferta horizontal por coorte', 'Coortes', 'method'], ['Ticket, área e R$/m² horizontal', 'Indicadores de preço', 'method'], ['VGV', 'Abertura de bloco', 'divider'], ['VGV ofertado, disponível e vendido por padrão', 'Matriz de VGV', 'method'], ['Análises', 'Abertura de bloco', 'divider'], ['Análise de mercado', 'Narrativa orientada por dados', 'narrative'], ['Análise de mercado', 'Narrativa orientada por dados', 'narrative'], ['Mapa', 'Abertura de bloco', 'divider'], ['Mapa de empreendimentos verticais', 'Visualização geográfica', 'map'], ['Consultores', 'Abertura', 'divider'], ['Créditos', 'Equipe e fontes', 'credits'], ['Brain Inteligência Estratégica', 'Encerramento', 'closing'], ['Panorama imobiliário', 'Encerramento', 'closing'], ['Obrigado', 'Encerramento', 'closing'], ['Fontes, premissas e rastreabilidade', 'Encerramento técnico', 'closing'],
];
/** Slide 2 is a redundant municipal cover; preserve reference numbering while omitting it from output. */
export const PANORAMA_REPORT_MANIFEST: ReportPageDefinition[] = pages.map(([title, intention, template], index) => ({ page: index + 1, title, intention, template })).filter((page) => page.page !== 2);
