import { useMemo, useState } from 'react';
import { ChevronLeft, ChevronRight, Download, FileText } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Button } from '@/components/ui/button';
import type { LaunchModel, PanoramaScope } from '../types';
import { quarterLabel } from '../lib/launches';
import '../print/panorama-print.css';

const money = (value: number | null) => value === null ? '—' : `R$ ${value.toLocaleString('pt-BR', { maximumFractionDigits: 1 })} mi`;
const number = (value: number) => value.toLocaleString('pt-BR');

function Page({ children, index, title, scope }: { children: React.ReactNode; index: number; title: string; scope: PanoramaScope }) {
  return <section className="panorama-report-page rounded-xl border border-border bg-card shadow-sm" aria-label={`Página ${index}: ${title}`}>
    <div className="panorama-page-content">{children}</div>
    <footer className="panorama-page-footer">Fonte: Brain Inteligência Estratégica · {scope.city}/{scope.uf} · {quarterLabel(scope.endQuarter)} <span>{index}</span></footer>
  </section>;
}

function TypeChart({ title, data, unit = '' }: { title: string; data: { quarter: string; vertical: number; horizontal: number }[]; unit?: string }) {
  return <div className="h-full min-h-0"><h3 className="mb-2 text-base font-semibold">{title}</h3><ResponsiveContainer width="100%" height="88%"><LineChart data={data}><CartesianGrid strokeDasharray="3 3" opacity={0.35} /><XAxis dataKey="quarter" tickFormatter={quarterLabel} tick={{ fontSize: 9 }} interval={2} /><YAxis tick={{ fontSize: 9 }} width={42} /><Tooltip formatter={(value) => `${Number(value).toLocaleString('pt-BR')}${unit}`} labelFormatter={(value) => quarterLabel(String(value) as never)} /><Legend wrapperStyle={{ fontSize: 11 }} /><Line dataKey="vertical" name="Residencial vertical" stroke="hsl(var(--primary))" strokeWidth={2.5} dot={false} /><Line dataKey="horizontal" name="Condomínio de casas" stroke="hsl(var(--accent))" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer></div>;
}
function StandardChart({ title, data, moneyValue = false }: { title: string; data: { quarter: string; economic: number; other: number }[]; moneyValue?: boolean }) {
  return <div className="h-full min-h-0"><h3 className="mb-2 text-base font-semibold">{title}</h3><ResponsiveContainer width="100%" height="88%"><BarChart data={data}><CartesianGrid strokeDasharray="3 3" opacity={0.35} /><XAxis dataKey="quarter" tickFormatter={quarterLabel} tick={{ fontSize: 9 }} interval={2} /><YAxis tick={{ fontSize: 9 }} width={42} /><Tooltip formatter={(value) => moneyValue ? money(Number(value)) : number(Number(value))} labelFormatter={(value) => quarterLabel(String(value) as never)} /><Legend wrapperStyle={{ fontSize: 11 }} /><Bar dataKey="economic" name="Econômico" stackId="a" fill="hsl(var(--primary))" /><Bar dataKey="other" name="Demais padrões" stackId="a" fill="hsl(var(--accent))" /></BarChart></ResponsiveContainer></div>;
}

export function ReportPaginator({ model, scope }: { model: LaunchModel; scope: PanoramaScope }) {
  const [page, setPage] = useState(0);
  const snapshots = useMemo(() => model.projects.filter((item) => ['1T2022', '1T2023', '1T2024', '1T2025', '1T2026'].includes(item.quarter)), [model]);
  const pages = [
    <Page key="cover" index={1} title="Capa" scope={scope}><div className="flex h-full flex-col justify-between bg-gradient-to-br from-primary via-primary to-secondary p-10 text-primary-foreground"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] opacity-80">Brain Inteligência Estratégica</p><h2 className="mt-8 text-4xl font-heading font-semibold">Panorama Imobiliário</h2><p className="mt-3 text-xl">{scope.city} ({scope.uf}) · {quarterLabel(scope.endQuarter)}</p></div><p className="text-sm opacity-80">Relatório automatizado · versão em validação</p></div></Page>,
    <Page key="quality" index={2} title="Recorte e qualidade" scope={scope}><div className="space-y-6 p-8"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Visão do relatório</p><h2 className="text-3xl font-heading">Recorte e qualidade dos dados</h2></div><div className="grid grid-cols-3 gap-4">{[{ l: 'Período final', v: quarterLabel(scope.endQuarter) }, { l: 'Séries carregadas', v: String(model.quarters.length) }, { l: 'Avisos', v: String(model.warnings.length) }].map((item) => <div key={item.l} className="rounded-lg bg-muted p-4"><p className="text-xs text-muted-foreground">{item.l}</p><p className="mt-1 text-2xl font-semibold">{item.v}</p></div>)}</div><div className="rounded-lg border border-border p-4 text-sm"><p className="font-medium">Metodologia em validação</p><p className="mt-1 text-muted-foreground">VGV lançado e MCMV permanecem identificados como premissas até confirmação dos analistas.</p></div><div className="rounded-lg border border-warning/30 bg-warning/10 p-4 text-sm">[LLM NECESSÁRIO AQUI] — observação qualitativa sobre o mercado.</div></div></Page>,
    <Page key="quarter-table" index={3} title="Lançamentos por trimestre" scope={scope}><div className="p-7"><h2 className="text-2xl font-heading">Lançamentos por trimestre</h2><p className="mb-5 text-sm text-muted-foreground">Comparação dos primeiros trimestres · mercado residencial</p><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="py-2">Métrica</th>{snapshots.map((item) => <th key={item.quarter} className="py-2 text-right">{quarterLabel(item.quarter)}</th>)}</tr></thead><tbody>{[{ label: 'Empreendimentos', values: model.projects }, { label: 'Unidades lançadas', values: model.units }, { label: 'VGV lançado', values: model.vgv, monetary: true }].map((row) => <><tr key={`${row.label}-v`} className="border-b"><td className="py-2 font-medium">{row.label} · Vertical</td>{snapshots.map((item) => { const value = row.values.find((entry) => entry.quarter === item.quarter)?.vertical ?? 0; return <td key={item.quarter} className="py-2 text-right tabular-nums">{row.monetary ? money(value) : number(value)}</td>; })}</tr><tr key={`${row.label}-h`} className="border-b"><td className="py-2">{row.label} · Horizontal</td>{snapshots.map((item) => { const value = row.values.find((entry) => entry.quarter === item.quarter)?.horizontal ?? 0; return <td key={item.quarter} className="py-2 text-right tabular-nums">{row.monetary ? money(value) : number(value)}</td>; })}</tr></>)}</tbody></table></div></Page>,
    <Page key="annual" index={4} title="Lançamentos por ano" scope={scope}><div className="p-7"><h2 className="text-2xl font-heading">Lançamentos por ano</h2><p className="mb-5 text-sm text-muted-foreground">Totais derivados da série trimestral disponível.</p><table className="w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="py-2">Ano</th><th className="text-right">Empr. total</th><th className="text-right">Unidades</th><th className="text-right">VGV lançado</th></tr></thead><tbody>{model.annual.map((item) => <tr key={item.year} className="border-b"><td className="py-3 font-medium">{item.year}{item.year === Number(scope.endQuarter.slice(2)) ? '*' : ''}</td><td className="text-right">{number(item.projects.total)}</td><td className="text-right">{number(item.units.total)}</td><td className="text-right">{money(item.vgv.total)}</td></tr>)}</tbody></table></div></Page>,
    <Page key="projects-type" index={5} title="Empreendimentos por tipo" scope={scope}><div className="h-full p-7"><TypeChart title="Empreendimentos lançados por trimestre" data={model.projects} /></div></Page>,
    <Page key="projects-standard" index={6} title="Empreendimentos por padrão" scope={scope}><div className="h-full p-7"><StandardChart title="Empreendimentos verticais por padrão" data={model.projectStandards} /></div></Page>,
    <Page key="units-type" index={7} title="Unidades por tipo" scope={scope}><div className="h-full p-7"><TypeChart title="Unidades lançadas por trimestre" data={model.units} /></div></Page>,
    <Page key="units-standard" index={8} title="Unidades por padrão" scope={scope}><div className="h-full p-7"><StandardChart title="Unidades verticais por padrão" data={model.unitStandards} /></div></Page>,
    <Page key="vgv-type" index={9} title="VGV por tipo" scope={scope}><div className="h-full p-7"><TypeChart title="VGV lançado por trimestre (R$ milhões)" data={model.vgv} unit=" mi" /></div></Page>,
    <Page key="vgv-standard" index={10} title="VGV por padrão" scope={scope}><div className="h-full p-7"><StandardChart title="VGV vertical por padrão (R$ milhões)" data={model.vgvStandards.map((item) => ({ ...item, economic: item.economic ?? 0, other: item.other ?? 0 }))} moneyValue /></div></Page>,
    <Page key="sources" index={11} title="Fontes e premissas" scope={scope}><div className="space-y-5 p-8"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Transparência</p><h2 className="text-3xl font-heading">Fontes e premissas</h2></div><ul className="list-disc space-y-3 pl-5 text-sm text-muted-foreground"><li>Dados consultados com o token autenticado da Rebrain e escopo autorizado.</li><li>Contagem de empreendimentos, padrões e VGV lançado seguem contratos em validação.</li><li>MCMV não é inferido automaticamente pelo padrão Econômico.</li><li>Retornos de analistas alteram uma nova versão do gabarito, sem reescrever a referência v1.</li></ul>{model.warnings.length > 0 && <div className="rounded-lg bg-warning/10 p-3 text-sm text-warning">{model.warnings.join(' ')}</div>}</div></Page>,
  ];
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-primary" /><span className="text-sm font-medium">Página {page + 1} de {pages.length}</span></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => setPage((value) => Math.max(0, value - 1))} disabled={page === 0}><ChevronLeft /> Anterior</Button><Button variant="outline" size="sm" onClick={() => setPage((value) => Math.min(pages.length - 1, value + 1))} disabled={page === pages.length - 1}>Próxima <ChevronRight /></Button><Button size="sm" onClick={() => window.print()}><Download /> Exportar PDF</Button></div></div><div className="print:space-y-0"><div className="print:hidden">{pages[page]}</div><div className="hidden print:block">{pages}</div></div></div>;
}
