import { useState } from 'react';
import { ChevronLeft, ChevronRight, Download, FileText } from 'lucide-react';
import { Line, LineChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Button } from '@/components/ui/button';
import type { PanoramaReportModel } from '../types';
import { quarterLabel } from '../lib/launches';
import { PANORAMA_REPORT_MANIFEST, type ReportPageDefinition } from '../report/manifest';
import '../print/panorama-print.css';

const n = (v: number) => v.toLocaleString('pt-BR');
const cash = (v: number) => `R$ ${v.toLocaleString('pt-BR', { maximumFractionDigits: 1 })} mi`;
function Sheet({ page, report, children }: { page: ReportPageDefinition; report: PanoramaReportModel; children: React.ReactNode }) { return <section className="panorama-report-page rounded-xl border border-border bg-card shadow-sm"><div className="panorama-page-content">{children}</div><footer className="panorama-page-footer">Fonte: API GeoBrain · {report.scope.city}/{report.scope.uf} · {quarterLabel(report.scope.endQuarter)}<span>{page.page}</span></footer></section>; }
function Pending({ title }: { title: string }) { return <div className="flex h-full flex-col justify-between p-8"><div><p className="text-xs font-semibold uppercase tracking-widest text-warning">metodologia aberta</p><h2 className="mt-3 text-3xl font-heading">{title}</h2><p className="mt-5 max-w-2xl text-muted-foreground">Espaço editorial pronto para a visualização final. Os dados serão consultados exclusivamente na API quando o contrato de cálculo, universo e filtros for homologado.</p></div><div className="rounded-xl border border-warning/30 bg-warning/10 p-4 text-sm text-warning">Sem valor substituto: esta página não usa número de referência, mock ou dado hardcoded.</div></div>; }
function Chart({ title, report, metric }: { title: string; report: PanoramaReportModel; metric: 'projects' | 'units' | 'vgv' }) { const data = report.launches[metric]; return <div className="h-full p-7"><h2 className="text-2xl font-heading">{title}</h2><p className="mb-2 text-sm text-muted-foreground">Série observada na API até {quarterLabel(report.scope.endQuarter)}</p><div className="h-[80%]"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid strokeDasharray="3 3" opacity={.35}/><XAxis dataKey="quarter" tickFormatter={(v) => quarterLabel(v)} tick={{fontSize:9}} interval={2}/><YAxis tick={{fontSize:9}}/><Tooltip formatter={(v) => metric === 'vgv' ? cash(Number(v)) : n(Number(v))}/><Legend/><Line dataKey="vertical" name="Residencial vertical" stroke="hsl(var(--primary))" strokeWidth={2.5} dot={false}/><Line dataKey="horizontal" name="Condomínio de casas" stroke="hsl(var(--accent))" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div></div>; }
function Table({ report, annual, title }: { report: PanoramaReportModel; annual: boolean; title: string }) { const rows = annual ? report.launches.annual : report.launches.projects.filter((x) => x.quarter[0] === '1'); return <div className="p-8"><h2 className="text-3xl font-heading">{title}</h2><table className="mt-6 w-full text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="py-3">{annual ? 'Ano' : 'Período'}</th><th className="text-right">Empreendimentos</th><th className="text-right">Unidades</th><th className="text-right">VGV lançado</th></tr></thead><tbody>{rows.map((row) => { const project = annual ? row.projects : row; const units = annual ? row.units : report.launches.units.find((x) => x.quarter === row.quarter)!; const vgv = annual ? row.vgv : report.launches.vgv.find((x) => x.quarter === row.quarter)!; return <tr key={annual ? row.year : row.quarter} className="border-b"><td className="py-3 font-medium">{annual ? row.year : quarterLabel(row.quarter)}</td><td className="text-right">{n(project.total)}</td><td className="text-right">{n(units.total)}</td><td className="text-right">{cash(vgv.total)}</td></tr>; })}</tbody></table></div>; }
function Content({ page, report }: { page: ReportPageDefinition; report: PanoramaReportModel }) { const title = page.title.replace('{cidade}', report.scope.city); if (page.template === 'cover') return <div className="flex h-full flex-col justify-between bg-gradient-to-br from-primary via-primary to-secondary p-10 text-primary-foreground"><div><p className="text-xs font-semibold uppercase tracking-[.24em] opacity-80">Brain Inteligência Estratégica</p><h2 className="mt-8 text-4xl font-heading">{title}</h2><p className="mt-3 text-xl">{report.scope.city}/{report.scope.uf} · {quarterLabel(report.scope.endQuarter)}</p></div><p className="text-sm opacity-85">Relatório automatizado · versão metodológica em validação</p></div>;
 if (page.template === 'divider') return <div className="flex h-full items-end bg-muted p-10"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-primary">Panorama imobiliário</p><h2 className="mt-3 text-5xl font-heading">{title}</h2><p className="mt-4 text-muted-foreground">{page.intention}</p></div></div>;
 if (page.template === 'launch-table') return <Table title={title} report={report} annual={page.page === 13}/>;
 if (page.template === 'launch-chart') return <Chart title={title} report={report} metric={page.page <= 15 ? 'projects' : page.page <= 17 ? 'units' : 'vgv'}/>;
 if (page.template === 'summary') return <div className="p-8"><p className="text-xs font-semibold uppercase tracking-widest text-primary">{page.intention}</p><h2 className="mt-2 text-3xl font-heading">{title}</h2><div className="mt-8 grid grid-cols-3 gap-4">{[['Séries de lançamentos', String(report.launches.quarters.length)], ['Empreendimentos', n(report.launches.projects.reduce((s, x) => s + x.total, 0))], ['Estado da base', report.dataState === 'ready' ? 'Pronto' : 'Parcial']].map(([l,v]) => <div key={l} className="rounded-xl bg-muted p-5"><p className="text-sm text-muted-foreground">{l}</p><p className="mt-2 text-3xl font-semibold">{v}</p></div>)}</div></div>;
 if (page.template === 'narrative') return <div className="flex h-full flex-col justify-between p-8"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">{page.intention}</p><h2 className="mt-3 text-3xl font-heading">{title}</h2><p className="mt-6 max-w-3xl text-lg text-muted-foreground">[LLM necessário aqui] Texto analítico produzido somente sobre indicadores homologados deste recorte.</p></div><p className="text-sm text-muted-foreground">Dados consultados em {new Date(report.generatedAt).toLocaleString('pt-BR')}.</p></div>;
 if (page.template === 'credits' || page.template === 'closing') return <div className="flex h-full flex-col justify-between bg-primary p-10 text-primary-foreground"><div><p className="text-xs uppercase tracking-[.2em] opacity-80">{page.intention}</p><h2 className="mt-5 text-4xl font-heading">{title}</h2></div><p className="max-w-xl text-sm opacity-85">Fontes: API GeoBrain. O gabarito permanece restrito à calibração e nunca alimenta números deste PDF.</p></div>;
 return <Pending title={title}/>; }
export function ReportPaginator({ report }: { report: PanoramaReportModel }) { const [current,setCurrent] = useState(0); const page = PANORAMA_REPORT_MANIFEST[current]; const print = () => window.print(); return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-primary"/><span className="text-sm font-medium">Página {page.page} de {PANORAMA_REPORT_MANIFEST.length} · {page.intention}</span></div><div className="flex gap-2"><Button variant="outline" size="sm" disabled={!current} onClick={() => setCurrent(current-1)}><ChevronLeft/>Anterior</Button><Button variant="outline" size="sm" disabled={current===PANORAMA_REPORT_MANIFEST.length-1} onClick={() => setCurrent(current+1)}>Próxima<ChevronRight/></Button><Button size="sm" onClick={print}><Download/>Exportar PDF</Button></div></div><div className="print:space-y-0"><div className="print:hidden"><Sheet page={page} report={report}><Content page={page} report={report}/></Sheet></div><div className="hidden print:block">{PANORAMA_REPORT_MANIFEST.map((item) => <Sheet key={item.page} page={item} report={report}><Content page={item} report={report}/></Sheet>)}</div></div></div>; }
